#!/bin/bash

# Resolve the directory of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Load commands
for file in "$SCRIPT_DIR"/commands/*.sh; do
    source "$file"
done

# Check if a parameter was provided
if [ "$#" -eq 0 ]; then
    help
    exit 1
fi

# Retrieve the function name from the first parameter
function_name=$1

# Check if the function exists
if declare -f "$function_name" > /dev/null; then
    # Extract parameters starting from the 2nd one
    params=("${@:2}")

    # Call the function with the extracted parameters
    $function_name "${params[@]}"
else
    echo "Unknown command: $function_name"
    echo "Usage: $0 {md5|sha256}"
    exit 1
fi
