#!/bin/bash

# Configure the runtime environment for jobs.
#
# Configuration can be set at multiple levels including the organization,
# environment, user, and project.  The configuration files will be sourced
# in this order:
#
# 1) All projects should contain a config/pipeline.sh file.  This file
#    is generated by the lab new command.  It contains the project name
#    environment variable.
#
# 2) Default values for LAB_* environment variables are set by the
#    framework and are relative to the project directory.
#
# 3) An organization can provide an /etc/labrc file to set configuration
#    defaults for an entire organization.
#
# 4) A user can provide a ~/.labrc file in their home directory to specify
#    configuration specific to their projects.  If a user works in a lab
#    or on a team then this is a good place to source in a .labrc from
#    a lab/team shared location.
#
# 5) A project can provide a .labrc file in the project root directory
#    to set configuration specific to the project and relevant to all
#    users and environments.
#
# 6) A project can provide environment specific configuration by including
#    a file named <environment-name>.rc in the config/environments
#    directory, e.g. default.rc.  The default environment is "default" and
#    the lab new command automatically generates a default.sh file in the
#    config/environments folder. The file used is based on the LAB_ENV
#    environment variable.  This variable would generally be set in the
#    ~/.labrc file but could also be an environment variable set in the
#    user's shell configuration.

# Set the default environment if one doesn't exist.
if [ -z "$LAB_ENV" ]; then
  LAB_ENV="default"
fi

LAB_PROJECT_PATH=$(realpath ".")

# Bootstrap the framework runtime environment.
if [ -f "$LAB_PROJECT_PATH/config/pipeline.sh" ]; then
  source "$LAB_PROJECT_PATH/config/pipeline.sh" # shellcheck disable=SC1091
fi

# Set all the default paths.
LAB_LOGS_PATH=$(realpath "logs")
LAB_DATA_PATH=$(realpath "data")
LAB_RESULTS_PATH=$(realpath "results")
LAB_CONTAINER_PATH=$(realpath "bin/docker")
LAB_CONDA_PATH=$(realpath "bin/conda")

# Load the configuration files.
if [ -f /etc/labrc ]; then
  source /etc/labrc # shellcheck disable=SC1091
fi
if [ -f ~/.labrc ]; then
  source ~/.labrc # shellcheck disable=SC1090
fi
if [ -f "$LAB_PROJECT_PATH/.labrc" ]; then
  source "$LAB_PROJECT_PATH/.labrc" # shellcheck disable=SC1091
fi
if [ -f "$LAB_PROJECT_PATH/config/environments/$LAB_ENV.sh" ]; then
  source "$LAB_PROJECT_PATH/config/environments/$LAB_ENV.sh" # shellcheck disable=SC1090
fi

# Make sure all the configured paths exist.
if [ ! -d "$LAB_LOGS_PATH" ]; then
  mkdir -p "$LAB_LOGS_PATH"
fi
if [ ! -d "$LAB_DATA_PATH" ]; then
  mkdir -p "$LAB_DATA_PATH"
fi
if [ ! -d "$LAB_RESULTS_PATH" ]; then
  mkdir -p "$LAB_RESULTS_PATH"
fi
if [ ! -d "$LAB_CONTAINER_PATH" ]; then
  mkdir -p "$LAB_CONTAINER_PATH"
fi
if [ ! -d "$LAB_CONDA_PATH" ]; then
  mkdir -p "$LAB_CONDA_PATH"
fi

# Make all the variables visible in the runtime environment
export LAB_ENV
export LAB_PROJECT_NAME
export LAB_PROJECT_PATH
export LAB_LOGS_PATH
export LAB_DATA_PATH
export LAB_RESULTS_PATH
export LAB_CONTAINER_PATH
export LAB_CONDA_PATH
export LAB_RANDOM_SEED

